# 1 = yes, 0.5 = sometimes, 0 = no
OBJECTS = {
    "rhino": {
        "animal": 1,
        "food": 0,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 0,
        "tool": 0,
        "electronic": 0,
        "holdable": 0,
        "indoor": 0,
        "engine": 0,
        "used_for_work": 0,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 0
    },

    "dog": {
        "animal": 1,
        "food": 0,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 0,
        "tool": 0,
        "electronic": 0,
        "holdable": 0,
        "indoor": 0.5,
        "engine": 0,
        "used_for_work": 0,
        "four_wheels": 0,
        "pet": 1,
        "healthy": 0
    },

    "mouse": {
        "animal": 1,
        "food": 0,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 0,
        "tool": 0,
        "electronic": 0,
        "holdable": 1,
        "indoor": 0.5,
        "engine": 0,
        "used_for_work": 0,
        "four_wheels": 0,
        "pet": 0.5,
        "healthy": 0
    },

    "fork": {
        "animal": 0,
        "food": 0,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 0,
        "tool": 1,
        "electronic": 0,
        "holdable": 1,
        "indoor": 1,
        "engine": 0,
        "used_for_work": 0,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 0
    },

    "chair": {
        "animal": 0,
        "food": 0,
        "furniture": 1,
        "appliance": 0,
        "vehicle": 0,
        "tool": 0,
        "electronic": 0,
        "holdable": 0,
        "indoor": 0.5,
        "engine": 0,
        "used_for_work": 0.5,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 0
    },

    "refrigerator": {
        "animal": 0,
        "food": 0,
        "furniture": 0,
        "appliance": 1,
        "vehicle": 0,
        "tool": 0,
        "electronic": 1,
        "holdable": 0,
        "indoor": 1,
        "engine": 0,
        "used_for_work": 0,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 0
    },

    "toaster": {
        "animal": 0,
        "food": 0,
        "furniture": 0,
        "appliance": 1,
        "vehicle": 0,
        "tool": 0,
        "electronic": 1,
        "holdable": 1,
        "indoor": 1,
        "engine": 0,
        "used_for_work": 0,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 0
    },

    "computer": {
        "animal": 0,
        "food": 0,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 0,
        "tool": 0,
        "electronic": 1,
        "holdable": 0,
        "indoor": 1,
        "engine": 0,
        "used_for_work": 0.5,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 0
    },

    "phone": {
        "animal": 0,
        "food": 0,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 0,
        "tool": 0,
        "electronic": 1,
        "holdable": 1,
        "indoor": 1,
        "engine": 0,
        "used_for_work": 0.5,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 0
    },

    "car": {
        "animal": 0,
        "food": 0,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 1,
        "tool": 0,
        "electronic": 0.5,
        "holdable": 0,
        "indoor": 0,
        "engine": 1,
        "used_for_work": 0.5,
        "four_wheels": 1,
        "pet": 0,
        "healthy": 0
    },

    "bicycle": {
        "animal": 0,
        "food": 0,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 1,
        "tool": 0,
        "electronic": 0.5,
        "holdable": 0,
        "indoor": 0,
        "engine": 0,
        "used_for_work": 0.5,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 1
    },

    "motorcycle": {
        "animal": 0,
        "food": 0,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 1,
        "tool": 0,
        "electronic": 0.5,
        "holdable": 0,
        "indoor": 0,
        "engine": 1,
        "used_for_work": 0.5,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 0
    },

    "scooter": {
        "animal": 0,
        "food": 0,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 1,
        "tool": 0,
        "electronic": 0.5,
        "holdable": 1,
        "indoor": 0,
        "engine": 0,
        "used_for_work": 0,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 1
    },

    "apple": {
        "animal": 0,
        "food": 1,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 0,
        "tool": 0,
        "electronic": 0,
        "holdable": 1,
        "indoor": 0,
        "engine": 0,
        "used_for_work": 0,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 1
    },

    "cake": {
        "animal": 0,
        "food": 1,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 0,
        "tool": 0,
        "electronic": 0,
        "holdable": 1,
        "indoor": 1,
        "engine": 0,
        "used_for_work": 0,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 0
    },

    "book": {
        "animal": 0,
        "food": 0,
        "furniture": 0,
        "appliance": 0,
        "vehicle": 0,
        "tool": 0,
        "electronic": 0,
        "holdable": 1,
        "indoor": 1,
        "engine": 0,
        "used_for_work": 0.5,
        "four_wheels": 0,
        "pet": 0,
        "healthy": 0
    }
}
